development:
  database: beerconf_development
  validation_framework: :active_model
test:
  database: beerconf_test
  validation_framework: :active_model
production:
  validation_framework: :active_model
  database: <%= ENV['CLOUDANT_URL'] %>/beerconf_production