development:
  database: runconf_development
  validation_framework: :active_model
test:
  database: runconf_test
  validation_framework: :active_model
production:
  validation_framework: :active_model
  database: <%= ENV['CLOUDANT_URL'] %>/runconf_production